"""
AI utilities for Gemini API interactions.
Refactored to eliminate DRY violations.
"""

import os
import json
from typing import List, Tuple, Optional, Dict, Any
from PIL import Image
from google import genai
from google.genai import types
from dotenv import load_dotenv

from .utils import clean_json_response, IMAGE_MODEL, DEFAULT_MODEL

load_dotenv()


def get_client():
    """Get authenticated Gemini client."""
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY not found in environment variables")
    return genai.Client(api_key=api_key)


def _handle_api_error(e: Exception) -> None:
    """Handle common Gemini API errors with helpful messages."""
    error_msg = str(e).lower()
    if "quota" in error_msg or "billing" in error_msg or "payment" in error_msg:
        raise RuntimeError(
            "Gemini API Error: This tool requires a PAID API key with billing enabled.\n"
            "Free tier keys do not support image generation. Please:\n"
            "1. Visit https://aistudio.google.com/api-keys\n"
            "2. Enable billing on your Google Cloud project\n"
            f"Original error: {e}"
        )
    elif "api key" in error_msg or "authentication" in error_msg or "unauthorized" in error_msg:
        raise RuntimeError(
            "Gemini API Error: Invalid API key.\n"
            "Please check that your GEMINI_API_KEY environment variable is set correctly.\n"
            f"Original error: {e}"
        )
    else:
        raise RuntimeError(f"Gemini API Error: {e}")


def generate_slide(
    user_prompt: str,
    target_image: Optional[Image.Image] = None,
    style_reference_images: Optional[List[Image.Image]] = None,
    full_text_context: str = "",
    resolution: str = "4K",
    enable_search: bool = False
) -> Tuple[Image.Image, Optional[str]]:
    """
    Generate or edit a slide image using Gemini.
    
    This unified function handles both new slide generation and editing:
    - If target_image is provided: Edit existing slide
    - If target_image is None: Generate new slide from scratch
    
    Args:
        user_prompt: The generation/edit prompt
        target_image: Optional existing image to edit
        style_reference_images: Optional style reference images
        full_text_context: Optional document context
        resolution: Image resolution ("4K", "2K", etc.)
        enable_search: Whether to enable Google Search grounding
        
    Returns:
        Tuple of (generated PIL Image, optional text response)
    """
    client = get_client()
    
    # Build prompt parts
    prompt_parts = [user_prompt]
    
    if target_image:
        prompt_parts.append(target_image)
    
    if style_reference_images:
        prompt_parts.append("Match the visual style (fonts, colors, layout) of these reference images:")
        prompt_parts.extend(style_reference_images)
    
    if full_text_context:
        prompt_parts.append(f"DOCUMENT CONTEXT:\n{full_text_context}\n")
    
    # Build config
    config = types.GenerateContentConfig(
        response_modalities=['TEXT', 'IMAGE'],
        image_config=types.ImageConfig(image_size=resolution)
    )
    if enable_search:
        config.tools = [{"google_search": {}}]
    
    # Call API
    try:
        response = client.models.generate_content(
            model=IMAGE_MODEL,
            contents=prompt_parts,
            config=config
        )
    except Exception as e:
        _handle_api_error(e)
    
    # Extract response
    generated_image = None
    response_text = None
    
    if response.candidates and response.candidates[0].content.parts:
        for part in response.candidates[0].content.parts:
            if part.inline_data:
                from io import BytesIO
                generated_image = Image.open(BytesIO(part.inline_data.data))
            elif part.text:
                response_text = part.text
    
    if not generated_image:
        raise RuntimeError("No image generated by the model.")
    
    return generated_image, response_text


# Backwards compatibility aliases
def generate_edited_slide(
    target_image: Image.Image,
    style_reference_images: List[Image.Image],
    full_text_context: str,
    user_prompt: str,
    resolution: str = "4K",
    enable_search: bool = False
) -> Tuple[Image.Image, Optional[str]]:
    """Edit an existing slide. (Alias for generate_slide with target_image)"""
    return generate_slide(
        user_prompt=user_prompt,
        target_image=target_image,
        style_reference_images=style_reference_images,
        full_text_context=full_text_context,
        resolution=resolution,
        enable_search=enable_search
    )


def generate_new_slide(
    style_reference_images: List[Image.Image],
    user_prompt: str,
    full_text_context: str = "",
    resolution: str = "4K",
    enable_search: bool = False
) -> Tuple[Image.Image, Optional[str]]:
    """Generate a new slide from scratch. (Alias for generate_slide without target_image)"""
    return generate_slide(
        user_prompt=user_prompt,
        target_image=None,
        style_reference_images=style_reference_images,
        full_text_context=full_text_context,
        resolution=resolution,
        enable_search=enable_search
    )


def semantic_search_pages(
    page_texts: Dict[int, str],
    query: str,
    page_images: Optional[Dict[int, Image.Image]] = None,
    top_k: int = 5
) -> List[Dict[str, Any]]:
    """
    Performs semantic search across PDF pages using Gemini.
    
    Args:
        page_texts: Dict mapping page number (1-indexed) to extracted text
        query: The search query
        page_images: Optional dict mapping page number to PIL Image for visual search
        top_k: Maximum number of results to return
    
    Returns:
        List of dicts with keys: page, relevance, explanation, snippet
    """
    from . import prompts
    
    # Build pages content
    pages_content = ""
    for page_num in sorted(page_texts.keys()):
        text = page_texts[page_num]
        if len(text) > 1500:
            text = text[:1500] + "...[truncated]"
        pages_content += f"\n--- PAGE {page_num} ---\n{text}\n"
    
    prompt = prompts.SEMANTIC_SEARCH_PROMPT.format(
        query=query,
        top_k=top_k,
        pages_content=pages_content
    )
    
    # Build content list
    contents = [prompt]
    if page_images:
        contents.append("\nVisual content from pages:")
        for page_num in sorted(page_images.keys()):
            contents.append(f"\nPage {page_num} visual:")
            contents.append(page_images[page_num])
    
    # Call API
    client = get_client()
    config = types.GenerateContentConfig(
        response_modalities=['TEXT'],
        temperature=0.1,
    )
    
    try:
        response = client.models.generate_content(
            model=DEFAULT_MODEL,
            contents=contents,
            config=config
        )
    except Exception as e:
        error_msg = str(e).lower()
        if "api key" in error_msg or "authentication" in error_msg:
            raise RuntimeError(f"Gemini API Error: Invalid API key. {e}")
        raise RuntimeError(f"Gemini API Error: {e}")
    
    # Extract and parse response
    response_text = ""
    if response.candidates and response.candidates[0].content.parts:
        for part in response.candidates[0].content.parts:
            if part.text:
                response_text = part.text
                break
    
    result = clean_json_response(response_text)
    
    if isinstance(result, list):
        return result[:top_k]
    elif isinstance(result, dict) and "error" not in result:
        return []
    return []


def describe_page(page_image: Image.Image, page_text: str = "") -> str:
    """
    Gets a detailed description of a PDF page using Gemini vision.
    
    Args:
        page_image: PIL Image of the page
        page_text: Optional extracted text from the page
        
    Returns:
        Detailed description of the page content
    """
    from . import prompts
    
    client = get_client()
    
    contents = [prompts.DESCRIBE_PAGE_PROMPT, page_image]
    if page_text:
        contents.append(f"\nExtracted text for reference:\n{page_text[:1000]}")
    
    config = types.GenerateContentConfig(
        response_modalities=['TEXT'],
        temperature=0.3,
    )
    
    try:
        response = client.models.generate_content(
            model=DEFAULT_MODEL,
            contents=contents,
            config=config
        )
    except Exception as e:
        raise RuntimeError(f"Gemini API Error: {e}")
    
    if response.candidates and response.candidates[0].content.parts:
        for part in response.candidates[0].content.parts:
            if part.text:
                return part.text
    
    return "Could not describe page."
